export enum VALID_ENV_KEYS {
  GOOGLE_GEMINI_API_KEY = "GOOGLE_GEMINI_API_KEY",
  OPENAI_API_KEY = "OPENAI_API_KEY",
  OPENROUTER_API_KEY = "OPENROUTER_API_KEY",
  OPENAI_ORGANIZATION_ID = "OPENAI_ORGANIZATION_ID",
  AZURE_EMBEDDINGS_NAME = "AZURE_EMBEDDINGS_NAME",
  AZURE_OPENAI_ENDPOINT = "AZURE_OPENAI_ENDPOINT",
  AZURE_GPT_35_TURBO_NAME = "AZURE_GPT_35_TURBO_NAME",
  AZURE_GPT_45_VISION_NAME = "AZURE_GPT_45_VISION_NAME",
  AZURE_GPT_45_TURBO_NAME = "AZURE_GPT_45_TURBO_NAME"
}
